"""empty message

Revision ID: e1b8d27bdf80
Revises: 
Create Date: 2021-08-25 12:09:09.331750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b8d27bdf80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Caracteristique',
    sa.Column('Num_Acc_id', sa.Integer(), nullable=False),
    sa.Column('Date_Acc', sa.DateTime(), nullable=True),
    sa.Column('Lumiere_Acc', sa.Integer(), nullable=True),
    sa.Column('Departement_Acc', sa.String(), nullable=True),
    sa.Column('Commune_Acc', sa.String(), nullable=True),
    sa.Column('Agglomeration_Acc', sa.Integer(), nullable=True),
    sa.Column('Intersection_Acc', sa.Integer(), nullable=True),
    sa.Column('Meteo', sa.Integer(), nullable=True),
    sa.Column('Collision_Acc', sa.Integer(), nullable=True),
    sa.Column('Addresse_Acc', sa.String(), nullable=True),
    sa.Column('Latitude_Acc', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('Longitude_Acc', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.PrimaryKeyConstraint('Num_Acc_id')
    )
    op.create_table('user_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('role_permissions', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('Lieux',
    sa.Column('ID_Route', sa.Integer(), nullable=False),
    sa.Column('Categorie_Route', sa.Integer(), nullable=True),
    sa.Column('Numero_Route', sa.Integer(), nullable=True),
    sa.Column('Indice_num_Route', sa.Integer(), nullable=True),
    sa.Column('Indice_alphanum_Route', sa.String(length=5), nullable=True),
    sa.Column('Circulation_Route', sa.Integer(), nullable=True),
    sa.Column('Nb_voie_Route', sa.Integer(), nullable=True),
    sa.Column('Type_voie_Route', sa.Integer(), nullable=True),
    sa.Column('Declivite_Route', sa.Integer(), nullable=True),
    sa.Column('Num_borne_Route', sa.Integer(), nullable=True),
    sa.Column('Distance_borne_Route', sa.Integer(), nullable=True),
    sa.Column('Tracer_plan_Route', sa.Integer(), nullable=True),
    sa.Column('Largeur_TPC_Route', sa.Integer(), nullable=True),
    sa.Column('Largeur_Route', sa.Integer(), nullable=True),
    sa.Column('Surface_Route', sa.Integer(), nullable=True),
    sa.Column('Infrastruture_Route', sa.Integer(), nullable=True),
    sa.Column('Situation_Acc_Route', sa.Integer(), nullable=True),
    sa.Column('Vitesse_max_Route', sa.Integer(), nullable=True),
    sa.Column('Num_Acc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Num_Acc_id'], ['Caracteristique.Num_Acc_id'], ),
    sa.PrimaryKeyConstraint('ID_Route')
    )
    op.create_table('Vehicule',
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('Num_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Sens_circulation_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Categorie_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Obstacle_fixe_heurete_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Obstacle_mobile_heurete_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Point_choc_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Manoeuvre_avant_accident_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Type_motorisation_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Nb_occupant_Vehicule', sa.Integer(), nullable=True),
    sa.Column('Num_Acc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Num_Acc_id'], ['Caracteristique.Num_Acc_id'], ),
    sa.PrimaryKeyConstraint('id_vehicule')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('u_email', sa.String(length=60), nullable=False),
    sa.Column('u_password', sa.String(length=128), nullable=False),
    sa.Column('u_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_role_id'], ['user_role.role_id'], ),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_table('Usager',
    sa.Column('id_Usager', sa.Integer(), nullable=False),
    sa.Column('Place_Usager', sa.Integer(), nullable=True),
    sa.Column('Categorie_Usager', sa.Integer(), nullable=True),
    sa.Column('Gravblessure_Usager', sa.Integer(), nullable=True),
    sa.Column('Sexe_Usager', sa.Integer(), nullable=True),
    sa.Column('Anne_Naissance_Usager', sa.Integer(), nullable=True),
    sa.Column('Motif_Deplacer_Usager', sa.Integer(), nullable=True),
    sa.Column('Equipement_Secu_Usager', sa.Integer(), nullable=True),
    sa.Column('Localisation_pieton_Usager', sa.Integer(), nullable=True),
    sa.Column('Action_pieton_Usager', sa.String(), nullable=True),
    sa.Column('Nb_pieton_Usager', sa.Integer(), nullable=True),
    sa.Column('Num_Acc_id', sa.Integer(), nullable=True),
    sa.Column('id_Vehicule', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Num_Acc_id'], ['Caracteristique.Num_Acc_id'], ),
    sa.ForeignKeyConstraint(['id_Vehicule'], ['Vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_Usager')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usager')
    op.drop_table('user')
    op.drop_table('Vehicule')
    op.drop_table('Lieux')
    op.drop_table('user_role')
    op.drop_table('Caracteristique')
    # ### end Alembic commands ###
